server:
  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temp_db
    username: postgres
    password: postgres
  cloud:
    stream:
      bindings:
        stock-out-0:
          destination: test_1pc_be
      kafka:
        binder:
          transaction:
            producer:
              configuration:
                enable.idempotence: true
                acks: all
            transaction-id-prefix: tx-
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      security.protocol: PLAINTEXT
management:
  endpoints:
    web:
      exposure:
        include: '*'
